# -*- coding: utf-8 -*-
"""PEDOT:PSS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12itAyfuYRjfHEFbPi7OA_dSBMBKj8Ks_
"""

import numpy as np
import matplotlib.pyplot as plt
from google.colab import drive
from matplotlib.ticker import FuncFormatter
import matplotlib.font_manager as fm

plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.serif'] = ['DejaVu Serif']
plt.rcParams['font.size'] = 15
plt.rcParams['axes.titlesize'] = 18
plt.rcParams['axes.labelsize'] = 18
plt.rcParams['legend.fontsize'] = 14
plt.rcParams['xtick.labelsize'] = 16
plt.rcParams['ytick.labelsize'] = 16

def formato_coma(x, pos):
    return f"{x:.2f}".replace(".", ",")

# =====================================================
# CONECTAR GOOGLE DRIVE
# =====================================================

drive.mount('/content/drive')

# =====================================================
# RUTA DE LOS DATOS
# =====================================================

ruta_base = "/content/drive/MyDrive/Datos PEDOT/UV-Vis/Día 0/"

# =====================================================
# LISTA DE MUESTRAS
# =====================================================

muestras = [
    "01",
    "02",
    "03",
    "04",
    "05",
    "06",
    "07"
]

# =====================================================
# LÍMITES DEL ESPECTRO VISIBLE Y SENSIBILIDAD DEL OJO
# =====================================================

VISIBLE_MIN = 400
VISIBLE_MAX = 780

SENSIBILIDAD_MIN = 492
SENSIBILIDAD_MAX = 577

# =====================================================
# GRÁFICA COMPARATIVA GENERAL
# =====================================================

plt.figure(figsize=(10,7))


# =====================================================
# ALMACENAMIENTO DE RESULTADOS
# =====================================================

T_total_d0 = {}
T_visible_d0 = {}
T_sensibilidad_d0 = {}
wavelength_avg_dict = {}
transmittance_avg_dict = {}


# =====================================================
# PROCESAMIENTO DE CADA MUESTRA
# =====================================================

for muestra in muestras:

    # =================================================
    # LISTAS PARA ALMACENAR LOS ESPECTROS
    # =================================================

    transmittance_all = []

    # =================================================
    # GRÁFICA INDIVIDUAL DE LA MUESTRA
    # =================================================

    plt.figure(figsize=(9,6))

    # =================================================
    # LEER LOS 4 CONJUNTOS DE DATOS
    # =================================================

    for conjunto in range(1, 5):

        # ---------------------------------------------
        # NOMBRE DEL ARCHIVO
        # ---------------------------------------------

        file = ruta_base + f"d0-{muestra}-0{conjunto}.txt"

        # ---------------------------------------------
        # CARGAR DATOS
        # ---------------------------------------------

        data = np.genfromtxt(
            file,
            delimiter=";",
            skip_header=2,
            converters={
                0: lambda x: float(x.replace(",", ".")),
                1: lambda x: float(x.replace(",", "."))
            }
        )

        # ---------------------------------------------
        # EXTRAER COLUMNAS
        # ---------------------------------------------

        wavelength = data[:, 0]
        transmittance = data[:, 1]

        # ---------------------------------------------
        # ALMACENAR ESPECTRO
        # ---------------------------------------------

        transmittance_all.append(transmittance)

        # ---------------------------------------------
        # GRAFICAR CONJUNTO INDIVIDUAL
        # ---------------------------------------------

        plt.plot(
            wavelength,
            transmittance,
            label=f"Conjunto 0{conjunto}"
        )

    # =================================================
    # ESPECTRO PROMEDIO
    # =================================================

    transmittance_avg = np.mean(transmittance_all, axis=0)

    # =================================================
    # TRANSMITANCIA PROMEDIO TOTAL
    # =================================================

    T_promedio_total = np.mean(transmittance_avg)

    # =================================================
    # TRANSMITANCIA PROMEDIO EN EL VISIBLE
    # =================================================

    visible_mask = (
        (wavelength >= VISIBLE_MIN) &
        (wavelength <= VISIBLE_MAX)
    )

    T_promedio_visible = np.mean(
        transmittance_avg[visible_mask]
    )

    T_total_d0[muestra] = T_promedio_total
    T_visible_d0[muestra] = T_promedio_visible
    wavelength_avg_dict[muestra] = wavelength
    transmittance_avg_dict[muestra] = transmittance_avg

    # =================================================
    # TRANSMITANCIA PROMEDIO EN LA ZONA DE MAYOR
    # SENSIBILIDAD VISUAL (492–577 nm)
    # =================================================

    sensibilidad_mask = (
        (wavelength >= SENSIBILIDAD_MIN)
        &
        (wavelength <= SENSIBILIDAD_MAX)
    )

    T_promedio_sensibilidad = np.mean(
        transmittance_avg[sensibilidad_mask]
    )

    T_sensibilidad_d0[muestra] = T_promedio_sensibilidad

    # =================================================
    # PICO DE TRANSMITANCIA MÁXIMA
    # =================================================


    indice_max = np.argmax(transmittance_avg)

    transmitancia_max = transmittance_avg[indice_max]

    longitud_onda_max = wavelength[indice_max]

    # =================================================
    # RANGO ±50 PUNTOS ALREDEDOR DEL PICO
    # =================================================

    indice_inferior = max(0, indice_max - 50)
    indice_superior = min(
        len(transmittance_avg) - 1,
        indice_max + 50
    )

    lambda_inferior = wavelength[indice_inferior]
    lambda_superior = wavelength[indice_superior]

    # =================================================
    # MOSTRAR RESULTADOS
    # =================================================

    print("========================================")
    print(f"Muestra {muestra}")
    print(f"Transmitancia promedio total: {T_promedio_total:.6f}")
    print(f"Transmitancia promedio visible: {T_promedio_visible:.6f}")
    print("")
    print(f"Transmitancia promedio 492-577 nm:{T_promedio_sensibilidad:.6f}")
    print(f"Transmitancia máxima: {transmitancia_max:.6f}")
    print(f"Longitud de onda del máximo: {longitud_onda_max:.2f} nm")
    print("")
    print("Rango ±50 puntos alrededor del máximo:")
    print(f"Índice inicial: {indice_inferior}")
    print(f"Índice final: {indice_superior}")
    print(f"Longitud de onda inicial: {lambda_inferior:.2f} nm")
    print(f"Longitud de onda final: {lambda_superior:.2f} nm")
    print("========================================")

    # =================================================
    # GRAFICAR ESPECTRO PROMEDIO
    # =================================================

    plt.plot(
        wavelength,
        transmittance_avg,
        label="Promedio",
        linewidth=3
    )

    # =================================================
    # CONFIGURACIÓN DE LA GRÁFICA INDIVIDUAL
    # =================================================

    plt.xlabel("Longitud de onda (nm)")
    plt.ylabel("Transmitancia (%)")

    plt.title(
        f"Espectros de transmitancia de la muestra {muestra} - Día inicial"
    )

    plt.grid()

    plt.gca().yaxis.set_major_formatter(
    FuncFormatter(formato_coma)
    )

    plt.legend()


    # =================================================
    # AÑADIR A LA GRÁFICA COMPARATIVA GENERAL
    # =================================================

    plt.figure(1)

    plt.plot(
        wavelength,
        transmittance_avg,
        label=f"Muestra {muestra}"
    )

# =====================================================
# CONFIGURACIÓN DE LA GRÁFICA COMPARATIVA GENERAL
# =====================================================

plt.figure(1)

plt.xlabel("Longitud de onda (nm)")
plt.ylabel("Transmitancia (%)")

plt.title(
    "Comparación de espectros promedio de transmitancia - Día inicial"
)

plt.grid()
plt.legend()


plt.gca().yaxis.set_major_formatter(
    FuncFormatter(formato_coma)
)



plt.savefig(
    "Comparacion_Transmitancia_Dia0.png",
    dpi=300,
    bbox_inches="tight"
)
plt.show()

# =====================================================
# COMPARACIÓN DE ESPECTROS PROMEDIO
# MUESTRAS 05, 06 Y 07 - DÍA 0
# =====================================================

plt.figure(figsize=(10,6))

for muestra in ["05", "06", "07"]:

    plt.plot(
        wavelength_avg_dict[muestra],
        transmittance_avg_dict[muestra],
        linewidth=2,
        label=f"Muestra {muestra}"
    )

plt.xlabel("Longitud de onda (nm)")
plt.ylabel("Transmitancia (%)")

plt.title(
    "Comparación de espectros promedio de transmitancia de las muestras 05, 06 y 07 - Día inicial"
)

plt.grid()

plt.gca().yaxis.set_major_formatter(
    FuncFormatter(formato_coma)
)

plt.legend()

plt.show()

# =====================================================
# RUTA DE LOS DATOS DEL DÍA 2
# =====================================================

ruta_base = "/content/drive/MyDrive/Datos PEDOT/UV-Vis/Día 2/"

# =====================================================
# LISTA DE MUESTRAS
# =====================================================

muestras = [
    "05",
    "06",
    "07"
]

# =====================================================
# GRÁFICA COMPARATIVA GENERAL
# =====================================================

plt.figure(figsize=(10,7))

# =====================================================
# ALMACENAMIENTO DE RESULTADOS
# =====================================================

T_total_d2 = {}
T_visible_d2 = {}
T_sensibilidad_d2 = {}

wavelength_avg_dict_d2 = {}
transmittance_avg_dict_d2 = {}

# =====================================================
# PROCESAMIENTO DE CADA MUESTRA
# =====================================================

for muestra in muestras:

    transmittance_all = []

    plt.figure(figsize=(9,6))

    # =================================================
    # LEER LOS 4 CONJUNTOS DE DATOS
    # =================================================

    for conjunto in range(1, 5):

        file = ruta_base + f"d2-{muestra}-0{conjunto}.txt"

        data = np.genfromtxt(
            file,
            delimiter=";",
            skip_header=2,
            converters={
                0: lambda x: float(x.replace(",", ".")),
                1: lambda x: float(x.replace(",", "."))
            }
        )

        wavelength = data[:, 0]
        transmittance = data[:, 1]

        transmittance_all.append(transmittance)

        plt.plot(
            wavelength,
            transmittance,
            label=f"Conjunto 0{conjunto}"
        )

    # =================================================
    # ESPECTRO PROMEDIO
    # =================================================

    transmittance_avg = np.mean(
        transmittance_all,
        axis=0
    )

    # =================================================
    # TRANSMITANCIA PROMEDIO TOTAL
    # =================================================

    T_promedio_total = np.mean(
        transmittance_avg
    )

    # =================================================
    # TRANSMITANCIA PROMEDIO EN EL VISIBLE
    # =================================================

    visible_mask = (
        (wavelength >= VISIBLE_MIN)
        &
        (wavelength <= VISIBLE_MAX)
    )

    T_promedio_visible = np.mean(
        transmittance_avg[visible_mask]
    )

    # =================================================
    # TRANSMITANCIA PROMEDIO EN LA REGIÓN DE
    # MÁXIMA SENSIBILIDAD VISUAL (492–577 nm)
    # =================================================

    sensibilidad_mask = (
        (wavelength >= SENSIBILIDAD_MIN)
        &
        (wavelength <= SENSIBILIDAD_MAX)
    )

    T_promedio_sensibilidad = np.mean(
        transmittance_avg[sensibilidad_mask]
    )

    # =================================================
    # ALMACENAMIENTO DE RESULTADOS
    # =================================================

    T_total_d2[muestra] = T_promedio_total
    T_visible_d2[muestra] = T_promedio_visible
    T_sensibilidad_d2[muestra] = T_promedio_sensibilidad

    wavelength_avg_dict_d2[muestra] = wavelength
    transmittance_avg_dict_d2[muestra] = transmittance_avg

    # =================================================
    # MÁXIMO DEL ESPECTRO PROMEDIO
    # =================================================

    indice_max = np.argmax(
        transmittance_avg
    )

    transmitancia_max = (
        transmittance_avg[indice_max]
    )

    longitud_onda_max = (
        wavelength[indice_max]
    )

    # =================================================
    # RANGO ±50 PUNTOS
    # =================================================

    indice_inferior = max(
        0,
        indice_max - 50
    )

    indice_superior = min(
        len(transmittance_avg) - 1,
        indice_max + 50
    )

    lambda_inferior = (
        wavelength[indice_inferior]
    )

    lambda_superior = (
        wavelength[indice_superior]
    )

    # =================================================
    # RESULTADOS
    # =================================================

    print("========================================")
    print(f"Muestra {muestra}")
    print(f"Transmitancia promedio total: {T_promedio_total:.6f}")
    print(f"Transmitancia promedio visible: {T_promedio_visible:.6f}")
    print(f"Transmitancia promedio 492-577 nm: {T_promedio_sensibilidad:.6f}")
    print("")
    print(f"Transmitancia máxima: {transmitancia_max:.6f}")
    print(f"Longitud de onda del máximo: {longitud_onda_max:.2f} nm")
    print("")
    print("Rango ±50 puntos alrededor del máximo:")
    print(f"Índice inicial: {indice_inferior}")
    print(f"Índice final: {indice_superior}")
    print(f"Longitud de onda inicial: {lambda_inferior:.2f} nm")
    print(f"Longitud de onda final: {lambda_superior:.2f} nm")
    print("========================================")

    # =================================================
    # ESPECTRO PROMEDIO
    # =================================================

    plt.plot(
        wavelength,
        transmittance_avg,
        label="Promedio",
        linewidth=3
    )

    plt.xlabel("Longitud de onda (nm)")
    plt.ylabel("Transmitancia (%)")

    plt.title(
        f"Espectros de transmitancia de la muestra {muestra} - 2 días de inmersión"
    )

    plt.grid()
    plt.legend()

    plt.gca().yaxis.set_major_formatter(
        FuncFormatter(formato_coma)
    )

    # =================================================
    # AÑADIR A COMPARATIVA
    # =================================================

    plt.figure(1)

    plt.plot(
        wavelength,
        transmittance_avg,
        label=f"Muestra {muestra}"
    )

# =====================================================
# CONFIGURACIÓN COMPARATIVA
# =====================================================

plt.figure(1)

plt.xlabel("Longitud de onda (nm)")
plt.ylabel("Transmitancia (%)")

plt.title(
    "Comparación de espectros promedio de transmitancia - 2 días de inmersión"
)

plt.grid()
plt.legend()

plt.gca().yaxis.set_major_formatter(
    FuncFormatter(formato_coma)
)

plt.show()

# =====================================================
# RUTA DE LOS DATOS DEL DÍA 7
# =====================================================

ruta_base = "/content/drive/MyDrive/Datos PEDOT/UV-Vis/Día 7/"

# =====================================================
# LISTA DE MUESTRAS
# =====================================================

muestras = [
    "05",
    "06",
    "07"
]

# =====================================================
# GRÁFICA COMPARATIVA GENERAL
# =====================================================

plt.figure(figsize=(10,7))

# =====================================================
# ALMACENAMIENTO DE RESULTADOS
# =====================================================

T_total_d7 = {}
T_visible_d7 = {}
T_sensibilidad_d7 = {}

# =====================================================
# PROCESAMIENTO DE CADA MUESTRA
# =====================================================

for muestra in muestras:

    transmittance_all = []

    plt.figure(figsize=(9,6))

    # =================================================
    # LEER LOS 4 CONJUNTOS DE DATOS
    # =================================================

    for conjunto in range(1, 5):

        file = ruta_base + f"d7-{muestra}-0{conjunto}.txt"

        data = np.genfromtxt(
            file,
            delimiter=";",
            skip_header=2,
            converters={
                0: lambda x: float(x.replace(",", ".")),
                1: lambda x: float(x.replace(",", "."))
            }
        )

        wavelength = data[:, 0]
        transmittance = data[:, 1]

        transmittance_all.append(transmittance)

        plt.plot(
            wavelength,
            transmittance,
            label=f"Conjunto 0{conjunto}"
        )

    # =================================================
    # ESPECTRO PROMEDIO
    # =================================================

    transmittance_avg = np.mean(
        transmittance_all,
        axis=0
    )

    # =================================================
    # TRANSMITANCIA PROMEDIO TOTAL
    # =================================================

    T_promedio_total = np.mean(
        transmittance_avg
    )

    # =================================================
    # TRANSMITANCIA PROMEDIO VISIBLE
    # =================================================

    visible_mask = (
        (wavelength >= VISIBLE_MIN)
        &
        (wavelength <= VISIBLE_MAX)
    )

    T_promedio_visible = np.mean(
        transmittance_avg[visible_mask]
    )

    # =================================================
    # TRANSMITANCIA PROMEDIO EN LA REGIÓN DE
    # MÁXIMA SENSIBILIDAD VISUAL (492–577 nm)
    # =================================================

    sensibilidad_mask = (
        (wavelength >= SENSIBILIDAD_MIN)
        &
        (wavelength <= SENSIBILIDAD_MAX)
    )

    T_promedio_sensibilidad = np.mean(
        transmittance_avg[sensibilidad_mask]
    )

    # =================================================
    # ALMACENAMIENTO DE RESULTADOS
    # =================================================

    T_total_d7[muestra] = T_promedio_total
    T_visible_d7[muestra] = T_promedio_visible
    T_sensibilidad_d7[muestra] = T_promedio_sensibilidad

    # =================================================
    # MÁXIMO DEL ESPECTRO PROMEDIO
    # =================================================

    indice_max = np.argmax(
        transmittance_avg
    )

    transmitancia_max = (
        transmittance_avg[indice_max]
    )

    longitud_onda_max = (
        wavelength[indice_max]
    )

    # =================================================
    # RANGO ±50 PUNTOS
    # =================================================

    indice_inferior = max(
        0,
        indice_max - 50
    )

    indice_superior = min(
        len(transmittance_avg) - 1,
        indice_max + 50
    )

    lambda_inferior = (
        wavelength[indice_inferior]
    )

    lambda_superior = (
        wavelength[indice_superior]
    )

    # =================================================
    # RESULTADOS
    # =================================================

    print("========================================")
    print(f"Muestra {muestra}")
    print(f"Transmitancia promedio total: {T_promedio_total:.6f}")
    print(f"Transmitancia promedio visible: {T_promedio_visible:.6f}")
    print(f"Transmitancia promedio 492-577 nm: {T_promedio_sensibilidad:.6f}")
    print("")
    print(f"Transmitancia máxima: {transmitancia_max:.6f}")
    print(f"Longitud de onda del máximo: {longitud_onda_max:.2f} nm")
    print("")
    print("Rango ±50 puntos alrededor del máximo:")
    print(f"Índice inicial: {indice_inferior}")
    print(f"Índice final: {indice_superior}")
    print(f"Longitud de onda inicial: {lambda_inferior:.2f} nm")
    print(f"Longitud de onda final: {lambda_superior:.2f} nm")
    print("========================================")

    # =================================================
    # ESPECTRO PROMEDIO
    # =================================================

    plt.plot(
        wavelength,
        transmittance_avg,
        label="Promedio",
        linewidth=3
    )

    plt.xlabel("Longitud de onda (nm)")
    plt.ylabel("Transmitancia (%)")

    plt.title(
        f"Espectros de transmitancia de la muestra {muestra} - Día 7"
    )

    plt.grid()
    plt.legend()

    plt.gca().yaxis.set_major_formatter(
        FuncFormatter(formato_coma)
    )

    # =================================================
    # AÑADIR A COMPARATIVA
    # =================================================

    plt.figure(1)

    plt.plot(
        wavelength,
        transmittance_avg,
        label=f"Muestra {muestra}"
    )

# =====================================================
# CONFIGURACIÓN COMPARATIVA
# =====================================================

plt.figure(1)

plt.xlabel("Longitud de onda (nm)")
plt.ylabel("Transmitancia (%)")

plt.title(
    "Comparación de espectros promedio de transmitancia - Día 7"
)

plt.grid()
plt.legend()

plt.gca().yaxis.set_major_formatter(
    FuncFormatter(formato_coma)
)

plt.show()

#Transmitancia promedio total vs tiempo

plt.figure(figsize=(8,6))

dias = [0, 2, 7]

for muestra in ["05", "06", "07"]:

    valores = [
        T_total_d0[muestra],
        T_total_d2[muestra],
        T_total_d7[muestra]
    ]

    plt.plot(
        dias,
        valores,
        marker="o",
        linewidth=2,
        label=f"Muestra {muestra}"
    )

plt.xlabel("Tiempo de inmersión (días)")
plt.ylabel("Transmitancia promedio (%)")

plt.title(
    "Evolución de la transmitancia promedio durante la inmersión"
)

plt.gca().yaxis.set_major_formatter(
    FuncFormatter(formato_coma)
)
plt.xticks(dias)
plt.grid()
plt.legend()

plt.show()

#Transmitancia visible

plt.figure(figsize=(8,6))

dias = [0, 2, 7]

for muestra in ["05", "06", "07"]:

    valores = [
        T_visible_d0[muestra],
        T_visible_d2[muestra],
        T_visible_d7[muestra]
    ]

    plt.plot(
        dias,
        valores,
        marker="o",
        linewidth=2,
        label=f"Muestra {muestra}"
    )

plt.xlabel("Tiempo de inmersión (días)")
plt.ylabel("Transmitancia promedio (%)")

plt.title(
    "Evolución de la transmitancia promedio en la región visible"
)
plt.xticks(dias)
plt.grid()
plt.legend()

plt.show()

# =====================================================
# EVOLUCIÓN DE LA TRANSMITANCIA PROMEDIO
# EN LA REGIÓN DE MÁXIMA SENSIBILIDAD VISUAL
# (492–577 nm)
# =====================================================

plt.figure(figsize=(8,6))

dias = [0, 2, 7]

for muestra in ["05", "06", "07"]:

    transmitancias = [
        T_sensibilidad_d0[muestra],
        T_sensibilidad_d2[muestra],
        T_sensibilidad_d7[muestra]
    ]

    plt.plot(
        dias,
        transmitancias,
        marker="o",
        linewidth=2,
        label=f"Muestra {muestra}"
    )

plt.xlabel("Tiempo de inmersión (días)")
plt.ylabel("Transmitancia promedio (%)")

plt.title(
    "Evolución de la transmitancia promedio en la región de máxima sensibilidad visual"
)

plt.xticks(dias)

plt.grid(True)

plt.gca().yaxis.set_major_formatter(
    FuncFormatter(formato_coma)
)

plt.legend()

plt.show()

#PARA RESISTENCIA

# =====================================================
# RUTA DE LOS DATOS
# =====================================================

ruta_base = "/content/drive/MyDrive/Datos PEDOT/Resis/Día 0/"

# =====================================================
# MUESTRAS
# =====================================================

muestras = [
    "01",
    "02",
    "03",
    "04",
    "05",
    "06",
    "07"
]

# =====================================================
# DIMENSIONES DE LAS MUESTRAS
# =====================================================

dimensiones = {
    "01": {"L": 2.06, "W": 1.54},
    "02": {"L": 1.98, "W": 1.22},
    "03": {"L": 2.06, "W": 1.58},
    "04": {"L": 2.02, "W": 1.53},
    "05": {"L": 2.14, "W": 0.97},
    "06": {"L": 2.07, "W": 0.96},
    "07": {"L": 2.10, "W": 1.00}
}

# =====================================================
# DICCIONARIO DE RESISTENCIAS
# =====================================================

R_d0 = {}

# =====================================================
# RECORRER MUESTRAS
# =====================================================

for muestra in muestras:

    archivo = ruta_base + f"D0-{muestra}.txt"

    # =================================================
    # CARGA DE DATOS
    # =================================================

    data = np.genfromtxt(
        archivo,
        delimiter=";",
        skip_header=1,
        converters={
            0: lambda x: float(x.replace(",", ".")),
            1: lambda x: float(x.replace(",", "."))
        }
    )

    corriente = data[:, 0]
    voltaje = data[:, 1]

    # =================================================
    # AJUSTE LINEAL
    # =================================================

    m, b = np.polyfit(
        corriente,
        voltaje,
        1
    )

    voltaje_ajuste = m * corriente + b

    # =================================================
    # CÁLCULO DE R²
    # =================================================

    ss_res = np.sum(
        (voltaje - voltaje_ajuste) ** 2
    )

    ss_tot = np.sum(
        (voltaje - np.mean(voltaje)) ** 2
    )

    r2 = 1 - ss_res / ss_tot

    # =================================================
    # RESISTENCIA
    # =================================================

    R = m

    L = dimensiones[muestra]["L"]
    W = dimensiones[muestra]["W"]

    Rsheet = (np.pi / np.log(2)) * R * (L / W)

    R_d0[muestra] = Rsheet

    print(f"Muestra {muestra}")
    print(f"Resistencia de lámina (Rsheet): {Rsheet:.6f} Ω/sq")
    print("========================================")

    # =================================================
    # RESULTADOS EN CONSOLA
    # =================================================

    print("========================================")
    print(f"Muestra {muestra}")
    print(f"Resistencia: {R:.4f} Ω")
    print(f"Intercepto: {b:.6e} V")
    print(f"R²: {r2:.6f}")
    print("========================================")

    # =================================================
    # GRÁFICA INDIVIDUAL
    # =================================================

    plt.figure(figsize=(8,6))

    # ---------------------------------------------
    # DATOS EXPERIMENTALES
    # ---------------------------------------------

    plt.scatter(
        corriente,
        voltaje,
        label="Datos experimentales",
        zorder=3
    )

    # ---------------------------------------------
    # AJUSTE LINEAL
    # ---------------------------------------------

    plt.plot(
        corriente,
        voltaje_ajuste,
        "--",
        linewidth=1,
        label="Ajuste lineal",
        zorder=2
    )

    # ---------------------------------------------
    # CAJA DE INFORMACIÓN
    # ---------------------------------------------

    if b >= 0:
      ecuacion = f"V = {m:.4f}I + {b:.4f}"
    else:
      ecuacion = f"V = {m:.4f}I - {abs(b):.4f}"

    texto_ajuste = (
      f"{ecuacion}\n"
      f"R² = {r2:.5f}\n"
      f"Resistencia = {R:.4f} Ω"
    )
    texto_ajuste = texto_ajuste.replace(".", ",")

    plt.text(
        0.05,
        0.95,
        texto_ajuste,
        transform=plt.gca().transAxes,
        verticalalignment="top",
        bbox=dict(
            boxstyle="round",
            facecolor="white",
            alpha=0.8
        )
    )

    # ---------------------------------------------
    # ETIQUETAS
    # ---------------------------------------------

    plt.xlabel("Corriente (A)")
    plt.ylabel("Voltaje (V)")

    plt.title(
        f"Voltaje en función de la corriente de la muestra {muestra} - Día inicial"
    )

    # ---------------------------------------------
    # CUADRÍCULA
    # ---------------------------------------------

    plt.grid(
        True,
        zorder=0
    )

    plt.gca().xaxis.set_major_formatter(
     FuncFormatter(formato_coma)
    )

    plt.gca().yaxis.set_major_formatter(
     FuncFormatter(formato_coma)
    )
    plt.legend()

# =====================================================
# GRÁFICA COMPARATIVA DE RESISTENCIAS
# =====================================================

plt.figure(figsize=(9,6))

muestras_x = list(R_d0.keys())
resistencias = list(R_d0.values())

barras = plt.bar(
    muestras_x,
    resistencias,
    zorder=3
)

# -----------------------------------------------------
# VALORES SOBRE CADA BARRA
# -----------------------------------------------------

for barra in barras:

    altura = barra.get_height()

    plt.text(
        barra.get_x() + barra.get_width()/2,
        altura,
        f"{altura:.3f}".replace(".", ","),
        ha="center",
        va="bottom"
    )

plt.xlabel("Muestra")
plt.ylabel("Resistencia (Ω/sq)")

plt.title(
    "Comparación de resistencias eléctricas de las muestras - Día inicial"
)

plt.grid(
    axis="y",
    zorder=0
)


plt.gca().yaxis.set_major_formatter(
     FuncFormatter(formato_coma)
)

plt.show()

# =====================================================
# RUTA DE LOS DATOS
# =====================================================

ruta_base = "/content/drive/MyDrive/Datos PEDOT/Resis/Día 2/"

# =====================================================
# MUESTRAS
# =====================================================

muestras = [
    "05",
    "06",
    "07"
]

# =====================================================
# DICCIONARIO DE RESISTENCIAS
# =====================================================

R_d2 = {}

# =====================================================
# RECORRER MUESTRAS
# =====================================================

for muestra in muestras:

    archivo = ruta_base + f"D2-{muestra}.txt"

    # =================================================
    # CARGA DE DATOS
    # =================================================

    data = np.genfromtxt(
        archivo,
        delimiter=";",
        skip_header=1,
        converters={
            0: lambda x: float(x.replace(",", ".")),
            1: lambda x: float(x.replace(",", "."))
        }
    )

    corriente = data[:, 0]
    voltaje = data[:, 1]

    # =================================================
    # AJUSTE LINEAL
    # =================================================

    m, b = np.polyfit(
        corriente,
        voltaje,
        1
    )

    voltaje_ajuste = m * corriente + b

    # =================================================
    # R²
    # =================================================

    ss_res = np.sum(
        (voltaje - voltaje_ajuste) ** 2
    )

    ss_tot = np.sum(
        (voltaje - np.mean(voltaje)) ** 2
    )

    r2 = 1 - ss_res / ss_tot

    # =================================================
    # RESISTENCIA
    # =================================================

    resistencia = m
    R = m

    L = dimensiones[muestra]["L"]
    W = dimensiones[muestra]["W"]

    Rsheet = (np.pi / np.log(2)) * R * (L / W)

    R_d2[muestra] = Rsheet

    print(f"Muestra {muestra}")
    print(f"Resistencia de lámina (Rsheet): {Rsheet:.6f} Ω/sq")
    print("========================================")

    # =================================================
    # RESULTADOS
    # =================================================

    print("========================================")
    print(f"Muestra {muestra}")
    print(f"Resistencia: {resistencia:.4f} Ω")
    print(f"Intercepto: {b:.4f} V")
    print(f"R²: {r2:.6f}")
    print("========================================")

    # =================================================
    # ECUACIÓN
    # =================================================

    if b >= 0:
        ecuacion = f"V = {m:.4f}I + {b:.4f}"
    else:
        ecuacion = f"V = {m:.4f}I - {abs(b):.4f}"

    texto_ajuste = (
        f"{ecuacion}\n"
        f"R² = {r2:.5f}\n"
        f"Resistencia = {resistencia:.4f} Ω"
    )

    texto_ajuste = texto_ajuste.replace(".", ",")



    # =================================================
    # GRÁFICA INDIVIDUAL
    # =================================================

    plt.figure(figsize=(8,6))

    plt.scatter(
        corriente,
        voltaje,
        label="Datos experimentales",
        zorder=3
    )

    plt.plot(
        corriente,
        voltaje_ajuste,
        "--",
        linewidth=1,
        label="Ajuste lineal",
        zorder=2
    )

    plt.text(
        0.05,
        0.95,
        texto_ajuste,
        transform=plt.gca().transAxes,
        verticalalignment="top",
        bbox=dict(
            boxstyle="round",
            facecolor="white",
            alpha=0.8
        )
    )

    plt.xlabel("Corriente (A)")
    plt.ylabel("Voltaje (V)")

    plt.title(
        f"Voltaje en función de la corriente de la muestra {muestra} - 2 días de inmersión"
    )

    plt.grid(
        True,
        zorder=0
    )

    plt.gca().xaxis.set_major_formatter(
     FuncFormatter(formato_coma)
    )

    plt.gca().yaxis.set_major_formatter(
     FuncFormatter(formato_coma)
    )

    plt.legend()

# =====================================================
# GRÁFICA COMPARATIVA DE RESISTENCIAS
# =====================================================

plt.figure(figsize=(9,6))

muestras_x = list(R_d2.keys())
resistencias = list(R_d2.values())

barras = plt.bar(
    muestras_x,
    resistencias,
    zorder=3
)

for barra in barras:

    altura = barra.get_height()

    plt.text(
        barra.get_x() + barra.get_width()/2,
        altura,
        f"{altura:.3f}".replace(".", ","),
        ha="center",
        va="bottom"
    )

plt.xlabel("Muestra")
plt.ylabel("Resistencia (Ω/sq)")

plt.title(
    "Comparación de resistencias eléctricas de las muestras - 2 días de inmersión"
)

plt.grid(
    axis="y",
    zorder=0
)

plt.gca().yaxis.set_major_formatter(
     FuncFormatter(formato_coma)
)



plt.show()

# =====================================================
# RUTA DE LOS DATOS
# =====================================================

ruta_base = "/content/drive/MyDrive/Datos PEDOT/Resis/Día 7/"

# =====================================================
# MUESTRAS
# =====================================================

muestras = [
    "05",
    "06",
    "07"
]

# =====================================================
# DICCIONARIO DE RESISTENCIAS
# =====================================================

R_d7 = {}

# =====================================================
# RECORRER MUESTRAS
# =====================================================

for muestra in muestras:

    archivo = ruta_base + f"D7-{muestra}.txt"

    # =================================================
    # CARGA DE DATOS
    # =================================================

    data = np.genfromtxt(
        archivo,
        delimiter=";",
        skip_header=1,
        converters={
            0: lambda x: float(x.replace(",", ".")),
            1: lambda x: float(x.replace(",", "."))
        }
    )

    corriente = data[:, 0]
    voltaje = data[:, 1]

    # =================================================
    # AJUSTE LINEAL
    # =================================================

    m, b = np.polyfit(
        corriente,
        voltaje,
        1
    )

    voltaje_ajuste = m * corriente + b

    # =================================================
    # R²
    # =================================================

    ss_res = np.sum(
        (voltaje - voltaje_ajuste) ** 2
    )

    ss_tot = np.sum(
        (voltaje - np.mean(voltaje)) ** 2
    )

    r2 = 1 - ss_res / ss_tot

    # =================================================
    # RESISTENCIA
    # =================================================

    resistencia = m
    R = m

    L = dimensiones[muestra]["L"]
    W = dimensiones[muestra]["W"]

    Rsheet = (np.pi / np.log(2)) * R * (L / W)

    R_d7[muestra] = Rsheet

    print(f"Muestra {muestra}")
    print(f"Resistencia de lámina (Rsheet): {Rsheet:.6f} Ω/sq")
    print("========================================")

    # =================================================
    # RESULTADOS
    # =================================================

    print("========================================")
    print(f"Muestra {muestra}")
    print(f"Resistencia: {resistencia:.4f} Ω")
    print(f"Intercepto: {b:.4f} V")
    print(f"R²: {r2:.6f}")
    print("========================================")

    # =================================================
    # ECUACIÓN
    # =================================================

    if b >= 0:
        ecuacion = f"V = {m:.4f}I + {b:.4f}"
    else:
        ecuacion = f"V = {m:.4f}I - {abs(b):.4f}"

    texto_ajuste = (
        f"{ecuacion}\n"
        f"R² = {r2:.5f}\n"
        f"Resistencia = {resistencia:.4f} Ω"
    )

    texto_ajuste = texto_ajuste.replace(".", ",")

    # =================================================
    # GRÁFICA INDIVIDUAL
    # =================================================

    plt.figure(figsize=(8,6))

    plt.scatter(
        corriente,
        voltaje,
        label="Datos experimentales",
        zorder=3
    )

    plt.plot(
        corriente,
        voltaje_ajuste,
        "--",
        linewidth=1,
        label="Ajuste lineal",
        zorder=2
    )

    plt.text(
        0.05,
        0.95,
        texto_ajuste,
        transform=plt.gca().transAxes,
        verticalalignment="top",
        bbox=dict(
            boxstyle="round",
            facecolor="white",
            alpha=0.8
        )
    )

    plt.xlabel("Corriente (A)")
    plt.ylabel("Voltaje (V)")

    plt.title(
        f"Voltaje en función de la corriente de la muestra {muestra} - Día 7"
    )

    plt.grid(
        True,
        zorder=0
    )

    plt.gca().xaxis.set_major_formatter(
     FuncFormatter(formato_coma)
    )

    plt.gca().yaxis.set_major_formatter(
     FuncFormatter(formato_coma)
    )

    plt.legend()

# =====================================================
# GRÁFICA COMPARATIVA DE RESISTENCIAS
# =====================================================

plt.figure(figsize=(9,6))

muestras_x = list(R_d7.keys())
resistencias = list(R_d7.values())

barras = plt.bar(
    muestras_x,
    resistencias,
    zorder=3
)

for barra in barras:

    altura = barra.get_height()

    plt.text(
        barra.get_x() + barra.get_width()/2,
        altura,
        f"{altura:.3f}".replace(".", ","),
        ha="center",
        va="bottom"
    )

plt.xlabel("Muestra")
plt.ylabel("Resistencia (Ω)")

plt.title(
    "Comparación de resistencias eléctricas de las muestras - Día 7"
)

plt.grid(
    axis="y",
    zorder=0
)


plt.gca().yaxis.set_major_formatter(
     FuncFormatter(formato_coma)
)

plt.show()

# =====================================================
# EVOLUCIÓN DE LA RESISTENCIA ELÉCTRICA
# =====================================================

plt.figure(figsize=(8,6))

dias = [0, 2, 7]

for muestra in ["05", "06", "07"]:

    resistencias = [
        R_d0[muestra],
        R_d2[muestra],
        R_d7[muestra]
    ]

    plt.plot(
        dias,
        resistencias,
        marker="o",
        linewidth=2,
        label=f"Muestra {muestra}"
    )



plt.xlabel("Tiempo de inmersión (días)")
plt.ylabel("Resistencia (Ω/sq)")

plt.title(
    "Evolución de la resistencia eléctrica durante la inmersión"
)

plt.xticks(dias)

plt.grid()
plt.legend()



plt.gca().yaxis.set_major_formatter(
     FuncFormatter(formato_coma)
)

plt.show()